# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _MtomUpload
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class uploadResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uploadResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uploadResult, name)
    __repr__ = _swig_repr
    __swig_setmethods__["chksum"] = _MtomUpload.uploadResult_chksum_set
    __swig_getmethods__["chksum"] = _MtomUpload.uploadResult_chksum_get
    if _newclass:chksum = _swig_property(_MtomUpload.uploadResult_chksum_get, _MtomUpload.uploadResult_chksum_set)
    __swig_setmethods__["uriFile"] = _MtomUpload.uploadResult_uriFile_set
    __swig_getmethods__["uriFile"] = _MtomUpload.uploadResult_uriFile_get
    if _newclass:uriFile = _swig_property(_MtomUpload.uploadResult_uriFile_get, _MtomUpload.uploadResult_uriFile_set)
    def __init__(self, *args): 
        this = _MtomUpload.new_uploadResult(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _MtomUpload.delete_uploadResult
    __del__ = lambda self : None;
uploadResult_swigregister = _MtomUpload.uploadResult_swigregister
uploadResult_swigregister(uploadResult)

class MtomUpload(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MtomUpload, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MtomUpload, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _MtomUpload.new_MtomUpload(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _MtomUpload.delete_MtomUpload
    __del__ = lambda self : None;
    def Upload(*args): return _MtomUpload.MtomUpload_Upload(*args)
    __swig_setmethods__["fd"] = _MtomUpload.MtomUpload_fd_set
    __swig_getmethods__["fd"] = _MtomUpload.MtomUpload_fd_get
    if _newclass:fd = _swig_property(_MtomUpload.MtomUpload_fd_get, _MtomUpload.MtomUpload_fd_set)
MtomUpload_swigregister = _MtomUpload.MtomUpload_swigregister
MtomUpload_swigregister(MtomUpload)



