
# #### CT Densitometric Calibration ####
# a (m_ROIntercept) : 
-0.0029775
# b (m_ROSlope): 
0.0007835

# apply calibration correction (m_ROCalibrationCorrectionIsActive): 
0

# #### Correction of the calibration ####
# Intervals Type (m_ROCalibrationCorrectionType) {SINGLE_INTERVAL = 0, THREE_INTERVALS = 1}: 
0
# R01 (m_RO1) : 
0
# R02 (m_RO2) : 
0
# a (m_RoCorrection1IntervalCoefficient0): 
0
# b (m_RoCorrection1IntervalCoefficient1): 
1

# R0 < R01
# a (m_RoCorrection3IntervalsFirstCoefficient0): 
0
# b (m_RoCorrectio3IntervalsFirstCoefficient1): 
1

# R01 <= R0 <= R02
# a (m_RoCorrection3IntervalsSecondCoefficient0): 
0
# b (m_RoCorrection3IntervalsSecondCoefficient1): 
1

# R0 > R02
# a (m_RoCorrection3IntervalsThirdCoefficient0): 
0
# b (m_RoCorrection3IntervalsThirdCoefficient1): 
1


# density-intervals for E integration
# Density intervals type (m_DensityIntervalsNumber) {SINGLE_INTERVAL = 0,THREE_INTERVALS = 1}: 
0

# R01 (m_RO1_RO2_el0): 
0
# R02 (m_RO1_RO2_el1): 
0
# a (m_Ea_Eb_Ec_V3_OneDensityInterval_el0): 
0
# b (m_Ea_Eb_Ec_V3_OneDensityInterval_el1): 
14664
# c (m_Ea_Eb_Ec_V3_OneDensityInterval_el2): 
1.49

# R0 < R01
# a (m_Ea0_Eb0_Ec0_V3_el0): 
0
# b (m_Ea0_Eb0_Ec0_V3_el1): 
1
# c (m_Ea0_Eb0_Ec0_V3_el2): 
1

# R01 <= R0 <= R02
# a (m_Ea1_Eb1_Ec1_V3_el0): 
0
# b (m_Ea1_Eb1_Ec1_V3_el1): 
1
# c (m_Ea1_Eb1_Ec1_V3_el2): 
1

# R0 > R02
# a (m_Ea2_Eb2_Ec2_V3_el0): 
0
# b (m_Ea2_Eb2_Ec2_V3_el1): 
1
# c (m_Ea2_Eb2_Ec2_V3_el2): 
1

# Young`s modulus (E) calculation modality
# Modality (m_YoungModuleCalculationModality) {HU_INTEGRATION = 0,YOUNG_MODULE_INTEGRATION = 1}: 
1

# Integration Steps (m_StepsNumber): 
4

# Gap Value (m_Egap): 
50

