<?xml version="1.0"?>
<!-- generated by wxGlade 0.5 on Sun Sep 16 15:51:58 2007 -->

<application path="D:\vapps\LHPBuilder_Parabuild\VMEUploaderDownloader\vmeUDGUI.py" name="VMEUploaderDownloader" class="" option="0" language="python" top_window="VmeUploaderDownloader" encoding="ISO-8859-1" use_gettext="0" overwrite="1" use_new_namespace="1" for_version="2.8" is_template="0">
    <object class="MyFrame" name="VmeUploaderDownloader" base="EditFrame">
        <style>wxDEFAULT_FRAME_STYLE</style>
        <title>vmeUploaderDownloaderGUI</title>
        <menubar>1</menubar>
        <statusbar>1</statusbar>
        <size>700, 500</size>
        <object class="wxMenuBar" name="frame_1_menubar" base="EditMenuBar">
            <menus>
                <menu name="" label="File">
                </menu>
                <menu name="" label="Edit">
                </menu>
                <menu name="" label="Operations">
                </menu>
                <menu name="" label="Help">
                </menu>
            </menus>
        </object>
        <object class="wxBoxSizer" name="sizer_1" base="EditBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizerslot" />
        </object>
        <object class="wxStatusBar" name="frame_1_statusbar" base="EditStatusBar">
            <fields>
                <field width="-1">frame_1_statusbar</field>
            </fields>
        </object>
    </object>
</application>
