#-----------------------------------------------------------------------------
# BEWARE!!! This is mostly a prototype!!!
# code is changing very fast so don't rely on it :P
# author: Stefano Perticoni <s.perticoni@scsolutions.it>
#-----------------------------------------------------------------------------

import os
import sys, string
import unittest
import shutil
from pyparsing import Word, alphas, nums, ZeroOrMore, Suppress, ParseException, Group, delimitedList, alphanums, Literal,Dict
import pprint

class pyparsingTest(unittest.TestCase):
            
    def testExample(self):
        
         # define grammar of a greeting
         greet = Word( alphas ) + "," + Word( alphas ) + "!" 
         
         hello = "Hello, World!"
         print hello, "->", greet.parseString( hello )      
                
         ciao = "Ciao, Pippo!"
         print ciao, "->", greet.parseString( ciao )      
        
    def testParseHeader(self):
        testHeader = """
!!! File input Ansys generato da hypermesh V7.0, commentato da Enrico, relativo ad una mesh di due elementi tetra10, con materiali, gia` usata come test-data in LhpB.
!!! I commenti con tre !!! sono miei, quelli con due !! arrivano direttamente da hypermesh
!! ANSYS Input Deck Generated by HyperMesh Version  : 7.0
!! Generated using HyperMesh-Ansys Template Version : 7.0
!!! le 5 righe seguenti si possono ignorare nell'importer, da riconsiderare per l'exporter
/TITLE,                                                                        
/COM,HyperMesh generated /PREP7 cards
/PREP7
DOF,  DELETE,        ,        ,        ,        ,        ,        ,        ,        ,        
/NOPR                                                                          
""" 
        lines = testHeader.splitlines()
        
#         print testHeader
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line
            # start grammar
            commentHeader = "!!" 
            commentText =  Group(ZeroOrMore("!") + ZeroOrMore(Word( alphas )))
            commentTextLine = commentHeader + commentText
            # end grammar
            try: 
                print commentTextLine.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
            lineNum += 1 
            #except ParseException:
                #print "Parsing exception!"
        
        
    def testParseNodes(self):
        nodesData  = """
!!! SEZIONE NODI, simil-matrice a 5 colonne separate da virgola 
!!!prima colonna: chiave identificativa (e` sempre il char N)
!!!seconda colonna: numero del nodo (sempre un intero)
!!!terza, quarta, quinta colonna: coordinate x,y,z del nodo (real)
!!!nota: la dichiarazione delle coord nodali non varia tra modelli tetra, hexa, lineari, quadratici. Eventuale mancanza quinta colonna in modelli 2D, quarta e quinta in modelli 1D (per ora non supportati)
CSYS,0 		!!!nota: questo campo indica il sistema di riferimento da utilizzare. il sistema 0 e cartesiano con origine 0,0,0. Ci poniamo il problema di altri sist di rif possibili o per ora no?

N,1,             0.0,             0.0,             0.0
N,2,             1.0,             0.0,             0.0
N,3,             0.0,             1.0,             0.0
N,4,             0.0,             0.0,             1.0
N,5,             1.0,             1.0,             1.0
N,6,             0.5,             0.0,             0.0
N,7,             0.0,             0.5,             0.0
N,8,             0.0,             0.0,             0.5
N,9,             0.5,             0.5,             0.0
N,10,             0.5,             0.0,             0.5
N,11,             1.0,             0.5,             0.5
N,12,             0.0,             0.5,             0.5
N,13,             0.5,             1.0,             0.5
N,14,             0.5,             0.5,             1.0
"""

        print nodesData
        
        lines = nodesData.splitlines()
        
#       print testHeader
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line
            # start grammar
            nodeHeader = "N,"
            nodeId = Word( alphanums ) + ","
            nodeCoords =  Group(delimitedList(Word( alphanums + ".")))
            nodeTextLine = nodeHeader + nodeId + nodeCoords
            # end grammar
            try: 
                print nodeTextLine.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
            lineNum += 1 
            #except ParseException:
                #print "Parsing exception!"
        
        
    def testReadMaterials(self):
        materialsData = """
!!!SEZIONE DEFINIZIONE MATERIALI
!!HMNAME MAT 

!!!Tre righe, la prima "MPTEMP" da ignorare (nell'import, NB potrebbe essere gia` commentata in alcuni file) e da non inserire (nell'export), la seconda e la terza da considerare sia per l'import che per l'export
!!!le righe da considerare hanno struttura a cinque colonne separate da virgola
!!!nota: tutte le righe che iniziano con MP sono relative alla dichiarazione di materiali, in particolare quelle con MPDATA definiscono le proprieta`
!!!prima colonna: identificazione di che cosa si tratta (e` una string, NB tutte le righe che iniziano con MP sono relative alla dichiarazione di materiali, in particolare quelle con MPDATA definiscono le proprieta`)
!!!seconda colonna: nome della proprieta` (string)
!!!terza colonna: numero del materiale NB questo e` importante perche` e` questo il parametro richiamato nella dichiarazione degli elementi, che fa associare un materiale ad un gruppo di elementi
!!!quarta colonna: 
!!!quinta colonna: 
!!!NB in questi file ci sono tre righe di dichiarazione, se ne potrebbero trovare di piu`, ma sempre con la stessa struttura

!!         2 "MAT2"
MPTEMP,1,             0.0
MPDATA,EX  ,2,1,          1000.0
MPDATA,NUXY,2,1,             0.3
!!HMNAME MAT 
!!         3 "MAT3"
MPTEMP,1,             0.0
MPDATA,EX  ,3,1,        200000.0
MPDATA,NUXY,3,1,            0.33
"""
        
        lines = materialsData.splitlines()
        
#       print testHeader
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line

            # start grammar
            materialTemp = "MPTEMP," + delimitedList(Word( alphanums + "."))
            materialData = "MPDATA," + delimitedList(Word( alphanums + "."))
            # end grammar
            
            try: 
                print materialTemp.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)

            try: 
                print materialData.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
           
            lineNum += 1 
            
         
    def testReadElementType(self):
        elementTypeData = """
!!!SEZIONE DICHIARAZIONE ELEMENT TYPE
!!!dichiara quanti "tipi" di elementi sono presenti NB ci possono essere diversi ET uguali, come i due qua sotto...)
!!!tre colonne, la prima (string) dice che sto creando un "element type", la seconda (intero) assegna un numero, la terza (intero) dice che tipo di elemento del DB ansys e` (ad es, 187 e` una particolare formulazione di tetra a 10 nodi) 
!!!NB io nell'import ignorerei queste righe, sono da considerare nell'export, ma sto pensando a un modo di evitare dichirazioni ridondanti come quella qua sotto
ET,2,187
ET,3,187
"""
        lines = elementTypeData.splitlines()
        
        # print elementTypeData
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line

            # start grammar
            elementTypeLine = "ET," + delimitedList(Word( nums ))
            # end grammar
            
            try: 
                print elementTypeLine.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)

            lineNum += 1 
            
    def testReadElementsDeclaration(self):
        elementTypeData = """
!!!SEZIONE DICHIARAZIONE ELEMENTI
!!!la dichiarazione di elementi avviene a gruppi (in questo caso sono 2). Ogni gruppo si puo` distinguere per "element type", "real constant set", "material"
!!HMNAME COMP 
!!   2-2-3 "TYPE2-REAL3-MAT2"
!!HMCOLOR COMP 
!!   2-2-3 1

!!!le righe seguenti definiscono il gruppo di elementi che hanno (type=2, material=2 real constant set=3) 
!!!NB a noi per ora (e per un po`...) non interessera` la distinzione per "real constant set", solo quelle per element type e per material. 
!!!Al momento consideriamo solo quelle per material, visto che le mesh hanno tipo di elemento uiniforme (tutti tetra 10, oppure tutti hexa 8 ecc.) 
!!!riga TYPE: ci interessa solo l'informazione "MAT,2", che dice che tutti gli elementi del gruppo hanno material card=2 (quella definita prima) 
!!!riga ESYS: definisce il sistema di riferimento dell'elemento. analogamente a quanto detto per i nodi, ci poniamo il problema di altri sist di rif possibili o per ora no?
!!!riga EN: definisce il numero elemento e la connettivita`. colonna1(string EN):dichiara che stiamo creando un elemento colonna2(intero): numero dell'elemento colonna3-->10: connettivita`, ovvero lista 
!!!dei nodi che compongono l'elemento (sono ordinati, in maniera nota per ciascun tipo di elemento in ANSYS...non serve vero?)
!!!riga EMORE: continuazione della definizione della connettivita`, poiche` il formato inp di ANSYS va a capo dopo 10 campi-colonna. In questo caso (elementi tetra 10) rimangono due nodi da listare
!!!NB ci saranno tante righe EN (ed eventualmente EMORE) quanti sono gli elementi contenuti nel gruppo (solo uno in questo caso) 
!!!NB a seconda del numero di nodi per ogni elemento per ogni riga EN ci potranno essere 0 (tetra 4, hexa8),1 (tetra 10),oppure 2 (hexa20) righe EMORE  
TYPE, 2  $ MAT, 2  $ REAL, 3
ESYS, 0
EN,       2,       3,       1,       2,       4,       7,       6,       9,      12
EMORE,       8,      10
!!!!le 5 righe seguenti sono comandi di selezione e raggruppamento di ANSYS, vanno ignorati nell'import, sono da riconsiderare per l'export 
ESEL, S, TYPE,,2
ESEL, R, MAT,,2
ESEL, R, REAL,,3
CM, TYPE2-REAL3-MAT2, ELEM
ESEL, ALL

!!!dichiarazione secondo gruppo elementi, analogo al primo...

!!HMNAME COMP 
!!   3-3-3 "TYPE3-REAL3-MAT3"
!!HMCOLOR COMP 
!!   3-3-3 1
TYPE, 3  $ MAT, 3  $ REAL, 3
ESYS, 0
EN,       1,       5,       2,       4,       3,      11,      10,      14,      13
EMORE,       9,      12
ESEL, S, TYPE,,3
ESEL, R, MAT,,3
ESEL, R, REAL,,3
CM, TYPE3-REAL3-MAT3, ELEM
ESEL, ALL
"""


#!!!SEZIONE DICHIARAZIONE ELEMENTI
#!!!la dichiarazione di elementi avviene a gruppi (in questo caso sono 2). Ogni gruppo si pu??stinguere per "element type", "real constant set", "material"
#!!HMNAME COMP 
#!!   2-2-3 "TYPE2-REAL3-MAT2"
#!!HMCOLOR COMP 
#!!   2-2-3 1

#!!!le righe seguenti definiscono il gruppo di elementi che hanno (type=2, material=2 real constant set=3) 
#!!!NB a noi per ora (e per un po'...) non interesser?a distinzione per "real constant set", solo quelle per element type e per material. Al momento consideriamo solo quelle per material, visto che le mesh hanno tipo di elemento uiniforme (tutti tetra 10, oppure tutti hexa 8 ecc.) 
#!!!riga TYPE: ci interessa solo l'informazione "MAT,2", che dice che tutti gli elementi del gruppo hanno material card=2 (quella definita prima) 
#!!!riga ESYS: definisce il sistema di riferimento dell'elemento. analogamente a quanto detto per i nodi, ci poniamo il problema di altri sist di rif possibili o per ora no?
#!!!riga EN: definisce il numero elemento e la connettivit?colonna1(string EN):dichiara che stiamo creando un elemento colonna2(intero): numero dell'elemento colonna3-->10: connettivit?ovvero lista dei nodi che compongono l'elemento (sono ordinati, in maniera nota per ciascun tipo di elemento in ANSYS...non serve vero?)
#!!!riga EMORE: continuazione della definizione della connettivit?poich?l formato inp di ANSYS va a capo dopo 10 campi-colonna. In questo caso (elementi tetra 10) rimangono due nodi da listare
#!!!NB ci saranno tante righe EN (ed eventualmente EMORE) quanti sono gli elementi contenuti nel gruppo (solo uno in questo caso) 
#!!!NB a seconda del numero di nodi per ogni elemento per ogni riga EN ci potranno essere 0 (tetra 4, hexa8),1 (tetra 10),oppure 2 (hexa20) righe EMORE  
#TYPE, 2  $ MAT, 2  $ REAL, 3
#ESYS, 0
#EN,       2,       3,       1,       2,       4,       7,       6,       9,      12
#EMORE,       8,      10
#!!!!le 5 righe seguenti sono comandi di selezione e raggruppamento di ANSYS, vanno ignorati nell'import, sono da riconsiderare per l'export 
#ESEL, S, TYPE,,2
#ESEL, R, MAT,,2
#ESEL, R, REAL,,3
#CM, TYPE2-REAL3-MAT2, ELEM
#ESEL, ALL
#
# ... -> will generate -> ...  
# 
# EN  Ty Mat Rea Esy Com
# 2   2   2   3   0   1      3     1     2     4     7     6     9    12    8    10
        
        lines = elementTypeData.splitlines()
        
        # print elementTypeData
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line

            # start grammar
            elementType = Suppress("TYPE,") + Word(nums)
            elementMat = Suppress("$") + Suppress(Word( alphas)) + Suppress(",") + Word( nums)
            elementReal = Suppress("$") + Suppress(Word( alphas)) + Suppress(",") + Word( nums)
            typeMatReal = elementType + elementMat + elementReal
            
            connectivityHeader  = Suppress("EN,")
            # connectivityId = Dict(Group(delimitedList(Word(nums))))
            elementId = Word(nums) + Suppress(",")
            connectivityList = delimitedList(Word(nums))
            connectivityLine = connectivityHeader + elementId + connectivityList
            
            moreConnectivityHeader  = Suppress("EMORE,")
            moreConnectivityId = delimitedList(Word(nums))
            moreConnectivityLine = moreConnectivityHeader + moreConnectivityId 
            # end grammar
                        
            
            try: 
                print typeMatReal.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
                
            try: 
                
                print connectivityLine.parseString(line)
                #print "data:", data
                #print "data.asList():",
                #pprint.pprint(data.asList())
                #print "data keys:", data.keys()
                #key = data.keys()[0]
                #print data[key]
                


            except ParseException:
                print "cannot parse line " + str(lineNum)
            
            try: 
                print moreConnectivityLine.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
            
            
            lineNum += 1 
  
if __name__ == '__main__':
    unittest.main()
    