#-----------------------------------------------------------------------------
# BEWARE!!! This is mostly a prototype!!!
# code is changing very fast so don't rely on it :P
# author: Stefano Perticoni <s.perticoni@scsolutions.it>
#-----------------------------------------------------------------------------

import os
import sys, string
import unittest
import shutil
from pyparsing import Word, alphas, nums, ZeroOrMore, ParseException, Group, delimitedList, alphanums
import pprint

class pyparsingTest(unittest.TestCase):
            
    def testExample(self):
        
         # define grammar of a greeting
         greet = Word( alphas ) + "," + Word( alphas ) + "!" 
         
         hello = "Hello, World!"
         print hello, "->", greet.parseString( hello )      
                
         ciao = "Ciao, Pippo!"
         print ciao, "->", greet.parseString( ciao )      
        
    def testParseHeader(self):
        testHeader = """
!!! File input Ansys generato da hypermesh V7.0, commentato da Enrico, relativo ad una mesh di due elementi tetra10, con materiali, gia` usata come test-data in LhpB.
!!! I commenti con tre !!! sono miei, quelli con due !! arrivano direttamente da hypermesh
!! ANSYS Input Deck Generated by HyperMesh Version  : 7.0
!! Generated using HyperMesh-Ansys Template Version : 7.0
!!! le 5 righe seguenti si possono ignorare nell'importer, da riconsiderare per l'exporter
/TITLE,                                                                        
/COM,HyperMesh generated /PREP7 cards
/PREP7
DOF,  DELETE,        ,        ,        ,        ,        ,        ,        ,        ,        
/NOPR                                                                          
""" 
        lines = testHeader.splitlines()
        
#         print testHeader
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line
            # start grammar
            commentHeader = "!!" 
            commentText =  Group(ZeroOrMore("!") + ZeroOrMore(Word( alphas )))
            commentTextLine = commentHeader + commentText
            # end grammar
            try: 
                print commentTextLine.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
            lineNum += 1 
            #except ParseException:
                #print "Parsing exception!"
        
        
    def testParseNodes(self):
        nodesData  = """
!!! SEZIONE NODI, simil-matrice a 5 colonne separate da virgola 
!!!prima colonna: chiave identificativa (e` sempre il char N)
!!!seconda colonna: numero del nodo (sempre un intero)
!!!terza, quarta, quinta colonna: coordinate x,y,z del nodo (real)
!!!nota: la dichiarazione delle coord nodali non varia tra modelli tetra, hexa, lineari, quadratici. Eventuale mancanza quinta colonna in modelli 2D, quarta e quinta in modelli 1D (per ora non supportati)
CSYS,0 		!!!nota: questo campo indica il sistema di riferimento da utilizzare. il sistema 0 e cartesiano con origine 0,0,0. Ci poniamo il problema di altri sist di rif possibili o per ora no?

N,1,             0.0,             0.0,             0.0
N,2,             1.0,             0.0,             0.0
N,3,             0.0,             1.0,             0.0
N,4,             0.0,             0.0,             1.0
N,5,             1.0,             1.0,             1.0
N,6,             0.5,             0.0,             0.0
N,7,             0.0,             0.5,             0.0
N,8,             0.0,             0.0,             0.5
N,9,             0.5,             0.5,             0.0
N,10,             0.5,             0.0,             0.5
N,11,             1.0,             0.5,             0.5
N,12,             0.0,             0.5,             0.5
N,13,             0.5,             1.0,             0.5
N,14,             0.5,             0.5,             1.0
"""

        print nodesData
        
        lines = nodesData.splitlines()
        
#       print testHeader
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line
            # start grammar
            nodeHeader = "N,"
            nodeId = Word( alphanums ) + ","
            nodeCoords =  Group(delimitedList(Word( alphanums + ".")))
            nodeTextLine = nodeHeader + nodeId + nodeCoords
            # end grammar
            try: 
                print nodeTextLine.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
            lineNum += 1 
            #except ParseException:
                #print "Parsing exception!"
        
        
    def testReadMaterials(self):
        materialsData = """
!!!SEZIONE DEFINIZIONE MATERIALI
!!HMNAME MAT 

!!!Tre righe, la prima "MPTEMP" da ignorare (nell'import, NB potrebbe essere gia` commentata in alcuni file) e da non inserire (nell'export), la seconda e la terza da considerare sia per l'import che per l'export
!!!le righe da considerare hanno struttura a cinque colonne separate da virgola
!!!nota: tutte le righe che iniziano con MP sono relative alla dichiarazione di materiali, in particolare quelle con MPDATA definiscono le proprieta`
!!!prima colonna: identificazione di che cosa si tratta (e` una string, NB tutte le righe che iniziano con MP sono relative alla dichiarazione di materiali, in particolare quelle con MPDATA definiscono le proprieta`)
!!!seconda colonna: nome della proprieta` (string)
!!!terza colonna: numero del materiale NB questo e` importante perche` e` questo il parametro richiamato nella dichiarazione degli elementi, che fa associare un materiale ad un gruppo di elementi
!!!quarta colonna: 
!!!quinta colonna: 
!!!NB in questi file ci sono tre righe di dichiarazione, se ne potrebbero trovare di piu`, ma sempre con la stessa struttura

!!         2 "MAT2"
MPTEMP,1,             0.0
MPDATA,EX  ,2,1,          1000.0
MPDATA,NUXY,2,1,             0.3
!!HMNAME MAT 
!!         3 "MAT3"
MPTEMP,1,             0.0
MPDATA,EX  ,3,1,        200000.0
MPDATA,NUXY,3,1,            0.33
"""
        
        lines = materialsData.splitlines()
        
#       print testHeader
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line

            # start grammar
            materialTemp = "MPTEMP," + delimitedList(Word( alphanums + "."))
            materialData = "MPDATA," + delimitedList(Word( alphanums + "."))
            # end grammar
            
            try: 
                print materialTemp.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)

            try: 
                print materialData.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)
           
            lineNum += 1 
            
         
    def testReadElementType(self):
        elementTypeData = """
!!!SEZIONE DICHIARAZIONE ELEMENT TYPE
!!!dichiara quanti "tipi" di elementi sono presenti NB ci possono essere diversi ET uguali, come i due qua sotto...)
!!!tre colonne, la prima (string) dice che sto creando un "element type", la seconda (intero) assegna un numero, la terza (intero) dice che tipo di elemento del DB ansys e` (ad es, 187 e` una particolare formulazione di tetra a 10 nodi) 
!!!NB io nell'import ignorerei queste righe, sono da considerare nell'export, ma sto pensando a un modo di evitare dichirazioni ridondanti come quella qua sotto
ET,2,187
ET,3,187
"""
        lines = elementTypeData.splitlines()
        
        # print elementTypeData
        lineNum = 0
        for line in lines:
            print str(lineNum) + " > " + line

            # start grammar
            elementType = "ET," + delimitedList(Word( nums ))
            # end grammar
            
            try: 
                print elementType.parseString( line )
            except ParseException:
                print "cannot parse line " + str(lineNum)

            lineNum += 1 
        
if __name__ == '__main__':
    unittest.main()
    