/*=========================================================================
Program:   Multimod Application Framework
Module:    $RCSfile: lhpOpDownloadVME.h,v $
Language:  C++
Date:      $Date: 2009-01-15 11:08:39 $
Version:   $Revision: 1.9.2.7 $
Authors:   Daniele Giunchi, Stefano Perticoni, Roberto Mucci
==========================================================================
Copyright (c) 2002/2007
SCS s.r.l. - BioComputing Competence Centre (www.scsolutions.it - www.b3c.it)

MafMedical Library use license agreement

The software named MafMedical Library and any accompanying documentation, 
manuals or data (hereafter collectively "SOFTWARE") is property of the SCS s.r.l.
This is an open-source copyright as follows:
Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, 
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, 
this list of conditions and the following disclaimer in the documentation and/or 
other materials provided with the distribution.
* Modified source versions must be plainly marked as such, and must not be misrepresented 
as being the original software.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' 
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR 
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

MafMedical is partially based on OpenMAF.
=========================================================================*/

#ifndef __lhpOpDownloadVME_H__
#define __lhpOpDownloadVME_H__

//----------------------------------------------------------------------------
// Include :
//----------------------------------------------------------------------------
#include "mafOp.h"

//----------------------------------------------------------------------------
// forward references :
//----------------------------------------------------------------------------
class lhpUser;
class mafVMEGroup;

//----------------------------------------------------------------------------
// lhpOpDownloadVME :
//----------------------------------------------------------------------------
/**Convert a Parametric Surface into a Normal Surface*/
class lhpOpDownloadVME: public mafOp
{
public:

	lhpOpDownloadVME(wxString label = "Download Vme");
	~lhpOpDownloadVME(); 

	mafTypeMacro(lhpOpDownloadVME, mafOp);

	mafOp* Copy();

  /** Class for handle mafEvent*/
  virtual void OnEvent(mafEventBase *maf_event);

	/** Return true for the acceptable vme type. */
	bool Accept(mafNode* vme);

	/** Builds operation's interface by calling CreateOpDialog() method. */
	void OpRun();

	/** Execute the operation. */
	virtual void OpDo();

  /** Set Current Working Msf Directory*/
  void SetMsfDir(mafString msfDir){m_MsfDir = msfDir;};

protected:

  /** This method is called at the end of the operation and result contain the wxOK or wxCANCEL. */
  virtual void OpStop(int result);

  /** Check if lhbbuilder software version is up to date in order to a allow vme uploading */
  bool IsLHPBuilderVersionUpToDate();

  /* Base Cache and Outgoing creation directory*/
  bool CreateIncomingDirectory();

  /** This method creates on filesystem a cache with msf and binary data that must be uploaded */
  bool CreateIncomingCache();

  /** This method checks if process exists and if there is a lock file */
  bool ExistsRunningProcess();

  /** Load configuration file for connection*/
  void SaveConnectionConfigurationFile();

  /** launch a script that open a selector after list all vme in basket, select them with a checklistbox */
  int CreateFileListFromBasket();

  /**Retrieve list from a file generated by selector script*/
  int RetrieveInformationFromBasketListFile();

  /**Retrieve list from a file generated by selector script*/
  int DownloadSelectedXMLFromBasket(mafString xmlFile);

  /** Reconstruct MSF from xml and binary file*/
  int ReconstructMSF(mafString  xmlFile);

  /** Import Reconstructed MSF*/
  int ImportMSF(mafNode *parentNode = NULL);

  /** Create a list of link URI */
  void GetLinkURI(mafNode *node);

  /** Create a list of child URI */
  wxArrayString GetChildURI(mafNode *node);

  /** Download a list of VME */
  int DownloadVME(wxArrayString listVME, mafNode *parentNode = NULL);  

  /** Download the whole MSF */
  int DownloadTree(mafNode *node);

  /** Call WS to send to the repository information about VMEs correctly downloaded */
  int DownloadCheck(bool failed = false);

  /** Call WS to check if resource that will be downloaded contains link */
  wxArrayString CheckRemoteLink(mafString URI);

  /** Call WS to check if resource that will be downloaded contains child */
  bool CheckRemoteChild(mafString URI);

  /** Call WS to check if resource that will be downloaded is a mafVMERoot*/
  bool CheckIsRoot(mafString URI);

  /** Rename old binary file into new name taking care of new VME id*/
  void UpdateBinaryFile();

  /** Rename old binary file into new name taking care of new VME id for animated VME*/
  void UpdateAnimatedBinaryFile();


  mafNode *m_NodeDownloaded;
  std::vector<mafNode*> m_DerivedNodeVector;
  std::vector<mafNode*> m_LinkNodeVector;
  std::vector<mafString> m_DownloadedURIVector;
  std::vector<mafString> m_CheckURIVector; //vector of dataresource that application tryed to download
  std::vector<mafNode*> m_DownloadedNodeVector;
  mafVMEGroup *m_RootGroup;
  mafVMEGroup *m_Group;

  lhpUser  *m_User;

  bool m_FillLinkVector;
  bool m_WholeMsfDownload;
  bool m_DebugMode;

  bool m_ENTERED;
  bool m_ENTERED2;

  int m_DownloadCounter;

 
  mafString m_CacheDir; //>cache superdirectory
  static mafString m_CacheSubdir; //>cache subdirectory
  mafString m_CurrentCache; //>current cache directory
  
  mafString m_IncomingDir; //directory for xml and binary to send
  mafString m_IncomingCompletePath; //directory for xml and binary to send

  mafString m_PythonUploadFullPath; //>directory where the scripts are
  mafString m_FileName; //>script file name
  mafString m_PythonExe; //>python  executable
  mafString m_PythonwExe; //>pythonw  executable
  mafString m_MsfDir; //>directory of original msf
  
  static long m_Pid; //> pid of the server process

  mafString m_BasketListFileName; 
  wxArrayString m_BasketListURI;
  wxArrayString m_ListLinkURI;
  wxArrayString m_ListLinkURIInTree;
  wxArrayString m_ListChildURI;

  mafString m_BinaryRealName;

  mafString m_URISRBFile;
  mafString m_URISRBFileSize;

  mafString m_ConnectionConfigurationFileName;
  mafString m_ProxyURL;
  mafString m_ProxyPort;
  mafString m_ServiceURL;
  
};
#endif