if(MAF_USE_BOOST)
  set(Boost_DIR ${BST_DIR})
  find_package(Boost REQUIRED CONFIG)
  if(Boost_FOUND)
#  LINK_LIBRARIES(${wxWidgets_LIBRARIES})
#    include_directories(${Boost_INCLUDE_DIRS})
  endif(Boost_FOUND)
endif(MAF_USE_BOOST)

if(MAF_USE_EIGEN)
  set(Eigen3_DIR ${EGN_DIR})
  find_package(Eigen3 REQUIRED CONFIG)
endif(MAF_USE_EIGEN)

if(MAF_USE_WX)
  set(wxWidgets_DIR ${WXW_DIR})
  find_package(wxWidgets REQUIRED CONFIG)#COMPONENTS adv core base aui CONFIG)
  if(wxWidgets_FOUND)
  endif(wxWidgets_FOUND)
endif(MAF_USE_WX)

if(MAF_USE_QT)
  find_package(Qt6 COMPONENTS Core Widgets REQUIRED)
endif(MAF_USE_QT)

if(MAF_USE_VTK)
  find_package(VTK REQUIRED CONFIG)
endif(MAF_USE_VTK)

if(MAF_USE_ITK)
  find_package(ITK REQUIRED CONFIG)
  if(ITK_FOUND)
  endif(ITK_FOUND)
endif(MAF_USE_ITK)

if(FTK_USE_XercesC)
  set(XercesC_DIR ${XRC_DIR})
  find_package(XercesC REQUIRED CONFIG)
  if(XercesC_FOUND)
  endif(XercesC_FOUND)
endif(FTK_USE_XercesC)

if(MAF_USE_CURL)
  set(CURL_DIR ${CRL_DIR})
  find_package(CURL REQUIRED CONFIG)
  if(CURL_FOUND)
  endif(CURL_FOUND)
endif(MAF_USE_CURL)

if(MAF_USE_CRYPTO)
  set(cryptopp_DIR ${CRP_DIR})
  find_package(cryptopp REQUIRED CONFIG)
  if(cryptopp_FOUND)
  endif(cryptopp_FOUND)
endif(MAF_USE_CRYPTO)

if(MAF_USE_Offis)
  find_package(DCMTK REQUIRED CONFIG)
  if(DCMTK_FOUND)
  endif(DCMTK_FOUND)
endif(MAF_USE_Offis)

if(MAF_USE_BTK)
  find_package(BTK REQUIRED)
  if(BTK_FOUND)
  endif(BTK_FOUND)
endif(MAF_USE_BTK)
