PROJECT (lhpWebServices_TEST)

# LINK_LIBRARIES(lhpNeededLibrary)

#-----------------------------------------------------------------------------
# tests using cppunit testing framework
#-----------------------------------------------------------------------------

# ADD_EXECUTABLE(yourTest yourTest.h yourTest.cpp)
# ADD_TEST(yourTest  ${EXECUTABLE_OUTPUT_PATH}/yourTest)

